services:
  postgres:
    image: postgres:16
    container_name: postgres_ape
    environment:
      POSTGRES_DB: ruv_db
      POSTGRES_USER: ruv_user
      POSTGRES_PASSWORD: ruv_password
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tablas_generales_v1.sql:/docker-entrypoint-initdb.d/tablas_generales_v1.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ruv_user -d ruv_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ruv-network

  api-service:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: api-service
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ruv-network

networks:
  ruv-network:
    driver: bridge

volumes:
  postgres_data:
