services:
  postgres:
    image: postgres:16
    container_name: postgres_ape
    environment:
      POSTGRES_DB: rav_ape_db1
      POSTGRES_USER: ravape_user
      POSTGRES_PASSWORD: Acceso_db1_rav_APE
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ravape_user -d rav_ape_db1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ape-network

  api-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile      
    container_name: api-service
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ape-network

networks:
  ape-network:
    driver: bridge

volumes:
  postgres_data:
