CREATE TABLE HIS_ORIENTACION_OFT (
HORIO_ID NUMBER,
TORI_ID NUMBER,
HORIO_FCH TIMESTAMP,
FUN_ID NUMBER(5,0),
PES_ID NUMBER,
OFT_ID NUMBER,
HORIO_DESCRIPCION VARCHAR2(255),
FECHA_REGISTRO DATE,
EVENTO_ID NUMBER,
PDC_ID NUMBER,
CONSTRAINT HIS_ORIENTACION_OFT_PK PRIMARY KEY (HORIO_ID),
CONSTRAINT SYS_C0021782 CHECK ("HORIO_ID" IS NOT NULL),
CONSTRAINT SYS_C0021783 CHECK ("TORI_ID" IS NOT NULL),
CONSTRAINT SYS_C0021784 CHECK ("HORIO_FCH" IS NOT NULL),
CONSTRAINT SYS_C0021785 CHECK ("FUN_ID" IS NOT NULL),
CONSTRAINT SYS_C0021786 CHECK ("OFT_ID" IS NOT NULL)
);

