CREATE TABLE SPE.HIS_ORIENTACION_OFT (
HORIO_ID NUMBER,
TORI_ID NUMBER,
HORIO_FCH TIMESTAMP,
FUN_ID NUMBER(5,0),
PES_ID NUMBER,
OFT_ID NUMBER,
HORIO_DESCRIPCION VARCHAR2(255),
FECHA_REGISTRO DATE,
EVENTO_ID NUMBER,
PDC_ID NUMBER,
CONSTRAINT HIS_ORIENTACION_OFT_PK PRIMARY KEY (HORIO_ID),
CONSTRAINT SYS_C0021782 CHECK ("HORIO_ID" IS NOT NULL),
CONSTRAINT SYS_C0021783 CHECK ("TORI_ID" IS NOT NULL),
CONSTRAINT SYS_C0021784 CHECK ("HORIO_FCH" IS NOT NULL),
CONSTRAINT SYS_C0021785 CHECK ("FUN_ID" IS NOT NULL),
CONSTRAINT SYS_C0021786 CHECK ("OFT_ID" IS NOT NULL)
);


CREATE UNIQUE INDEX HIS_ORIENTACION_OFT_PK ON SPE.HIS_ORIENTACION_OFT (HORIO_ID);


CREATE TABLE SPE.FUNCIONARIO (
FUN_ID NUMBER(5,0),
OFT_ID NUMBER(9,0),
FUN_FCH_REGISTRO DATE,
FUN_ESTADO NUMBER(1,0),
CSPE_ID NUMBER(7,0),
REG_ID NUMBER(2,0),
USR_NOMBRE VARCHAR2(50),
FUN_VER_TODAS_REGIONALES NUMBER(1,0) DEFAULT 0 ,
CONSTRAINT CSPE_FUN_NULL CHECK ("CSPE_ID" IS NOT NULL),
CONSTRAINT FUN_ESTADO_CHK CHECK (FUN_ESTADO in (0,1)),
CONSTRAINT FUN_ESTADO_NULL CHECK ("FUN_ESTADO" IS NOT NULL),
CONSTRAINT FUN_FCH_REGISTRO_NULL CHECK ("FUN_FCH_REGISTRO" IS NOT NULL),
CONSTRAINT FUN_ID_NULL CHECK ("FUN_ID" IS NOT NULL),
CONSTRAINT FUN_PK PRIMARY KEY (FUN_ID),
CONSTRAINT OFT_FUN_NULL CHECK ("OFT_ID" IS NOT NULL),
CONSTRAINT REG_FUN_NULL CHECK ("REG_ID" IS NOT NULL),
CONSTRAINT SYS_C0021347 CHECK ("FUN_VER_TODAS_REGIONALES" IS NOT NULL)
);

CREATE INDEX FUNCIONARIO_FUN_ESTADO ON SPE.FUNCIONARIO (FUN_ESTADO);

CREATE UNIQUE INDEX FUN_PK ON SPE.FUNCIONARIO (FUN_ID);

CREATE INDEX KD_FUNCIONARIO ON SPE.FUNCIONARIO (FUN_ID,REG_ID);

CREATE INDEX OFT_FUN_UK ON SPE.FUNCIONARIO (OFT_ID);



-- SPE. foreign keys

-- SPE.FUNCIONARIO foreign keys
ALTER TABLE SPE.FUNCIONARIO ADD CONSTRAINT CSPE_FUN_FK
FOREIGN KEY (CSPE_ID) REFERENCES SPE.CENTRO_SPE(CSPE_ID);

ALTER TABLE SPE.FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_SEC_USUARIO
FOREIGN KEY (USR_NOMBRE) REFERENCES SPE.SEC_USUARIO(USU_ID);

ALTER TABLE SPE.FUNCIONARIO ADD CONSTRAINT OFT_FUN_FK
FOREIGN KEY (OFT_ID) REFERENCES SPE.OFERTA(OFT_ID);

ALTER TABLE SPE.FUNCIONARIO ADD CONSTRAINT REG_FUN_FK
FOREIGN KEY (REG_ID) REFERENCES SPE.REGIONAL(REG_ID);


CREATE TABLE SPE.SEC_USUARIO (
	USU_ID VARCHAR2(255),
	TDI_ID NUMBER(1,0),
	USU_NUMERO_DOC NUMBER(20,0),
	USU_PASSWORD VARCHAR2(50),
	USU_ACTIVO NUMBER(1,0) DEFAULT 1,
	USU_BLOQUEADO NUMBER(1,0) DEFAULT 0,
	USU_EMAIL VARCHAR2(512),
	USU_FCH_REGISTRO DATE,
	USU_TIPO NUMBER(1,0) DEFAULT 0 ,
	CONSTRAINT SYS_C0022769 CHECK ("USU_ID" IS NOT NULL),
	CONSTRAINT SYS_C0022770 CHECK ("TDI_ID" IS NOT NULL),
	CONSTRAINT SYS_C0022771 CHECK ("USU_NUMERO_DOC" IS NOT NULL),
	CONSTRAINT SYS_C0022772 CHECK ("USU_PASSWORD" IS NOT NULL),
	CONSTRAINT SYS_C0022773 CHECK ("USU_TIPO" IS NOT NULL),
	CONSTRAINT SYS_C0024054 PRIMARY KEY (USU_ID)
);
DROP TABLE spe.sec_usuario
CREATE INDEX SUS_NUM_IDENTIFICACION ON SPE.SEC_USUARIO (USU_NUMERO_DOC);
CREATE UNIQUE INDEX SYS_C0024054 ON SPE.SEC_USUARIO (USU_ID);


CREATE TABLE SPE.OFERTA (
OFT_ID NUMBER(9,0),
TDI_ID NUMBER(1,0),
OFT_IDENTIFICACION NUMBER(20,0),
OFT_NOMBRES VARCHAR2(70),
OFT_PRIMER_APELLIDO VARCHAR2(40),
OFT_SEGUNDO_APELLIDO VARCHAR2(40),
OFT_GENERO NUMBER(1,0),
OFT_FCH_NACIMIENTO DATE,
ESC_ID NUMBER(1,0),
OFT_LIB_MILITAR NUMBER(1,0),
ETR_ID NUMBER(1,0),
PAI_ID NUMBER(3,0),
DPT_ID NUMBER(7,0),
MPO_ID NUMBER(9,0),
ZON_ID NUMBER(12,0),
BAR_ID NUMBER(6,0),
OFT_DIRECCION VARCHAR2(100),
OFT_TEL VARCHAR2(20),
OFT_EXT_TEL NUMBER(6,0),
OFT_TEL_ALT VARCHAR2(20),
OFT_EXT_TEL_ALT NUMBER(6,0),
OFT_TEL_CEL VARCHAR2(20),
OFT_BEEPER VARCHAR2(20),
OFT_CORREO_E VARCHAR2(50),
OFT_TIEMPO_BUSQUEDA NUMBER(4,0),
OFT_PERSONAS_CARGO NUMBER(2,0),
PSF_ID NUMBER(1,0),
OFT_MED_INSCRIPCION NUMBER(1,0),
OFT_AUTORIZACION VARCHAR2(1),
OFT_CLAVE NUMBER(10,0),
OFT_PREGUNTA VARCHAR2(40),
OFT_RESPUESTA VARCHAR2(40),
OFT_SUELDO_ACEPTARIA NUMBER(9,0),
OFT_SISBEN_NIVEL NUMBER(2,0),
OFT_SISBEN_PUNTAJE NUMBER(3,0),
OFT_SISBEN_TIPO NUMBER(1,0),
OFT_SISBEN_FCH_FIN DATE,
OFT_SISBEN_MPO NUMBER(9,0),
FUN_ID NUMBER(5,0),
CSPE_ID NUMBER(7,0),
REG_ID NUMBER(2,0),
FUN_ID_ACTUALIZA NUMBER(5,0),
CSPE_ID_ACTUALIZA NUMBER(7,0),
OFT_IDENTIFICACION_MPO NUMBER(9,0),
OFT_NACIMIENTO_MPO NUMBER(9,0),
SUE_ID NUMBER(3,0),
OFT_IND_TEL NUMBER(5,0),
OFT_IND_TEL_ALT NUMBER(5,0),
OFT_MIGRANTE NUMBER(1,0),
OFT_ES_RURAL NUMBER(1,0),
OFT_SOPORTE NUMBER(1,0),
OFT_SOPORTE_URL VARCHAR2(100),
OFT_TEL_CEL_ALT VARCHAR2(20),
OFT_TARJETA_IDENTIDAD NUMBER,
OFT_EVENTO NUMBER,
OFT_SOPORTE_OCCRE NUMBER(1,0),
OFT_OCCRE_URL VARCHAR2(100),
CONSTRAINT ESC_OFT_NULL CHECK ("ESC_ID" IS NOT NULL),
CONSTRAINT ETR_OFT_NULL CHECK ("ETR_ID" IS NOT NULL),
CONSTRAINT OFT_AUTORIZACION_CHK CHECK (OFT_AUTORIZACION in (0,1,2,3)),
CONSTRAINT OFT_AUTORIZACION_NULL CHECK ("OFT_AUTORIZACION" IS NOT NULL),
CONSTRAINT OFT_CLAVE_NULL CHECK ("OFT_CLAVE" IS NOT NULL),
CONSTRAINT OFT_DIRECCION_NULL CHECK ("OFT_DIRECCION" IS NOT NULL),
CONSTRAINT OFT_FCH_NACIMIENTO_NULL CHECK ("OFT_FCH_NACIMIENTO" IS NOT NULL),
CONSTRAINT OFT_GENERO_CHK CHECK (OFT_GENERO in (0,1)),
CONSTRAINT OFT_GENERO_NULL CHECK ("OFT_GENERO" IS NOT NULL),
CONSTRAINT OFT_IDENTIFICACION_NULL CHECK ("OFT_IDENTIFICACION" IS NOT NULL),
CONSTRAINT OFT_IDENTIFICACION_UK_UC UNIQUE (OFT_IDENTIFICACION),
CONSTRAINT OFT_ID_NULL CHECK ("OFT_ID" IS NOT NULL),
CONSTRAINT OFT_LIB_MILITAR_CHK CHECK (OFT_LIB_MILITAR in (0,1,2)),
CONSTRAINT OFT_LIB_MILITAR_NULL CHECK ("OFT_LIB_MILITAR" IS NOT NULL),
CONSTRAINT OFT_MED_INSCRIPCION_CHK CHECK (OFT_MED_INSCRIPCION in (0,1)),
CONSTRAINT OFT_MED_INSCRIPCION_NULL CHECK ("OFT_MED_INSCRIPCION" IS NOT NULL),
CONSTRAINT OFT_NOMBRES_NULL CHECK ("OFT_NOMBRES" IS NOT NULL),
CONSTRAINT OFT_PERSONAS_CARGO_NULL CHECK ("OFT_PERSONAS_CARGO" IS NOT NULL),
CONSTRAINT OFT_PK PRIMARY KEY (OFT_ID),
CONSTRAINT OFT_PREGUNTA_NULL CHECK ("OFT_PREGUNTA" IS NOT NULL),
CONSTRAINT OFT_PRIMER_APELLIDO_NULL CHECK ("OFT_PRIMER_APELLIDO" IS NOT NULL),
CONSTRAINT OFT_RESPUESTA_NULL CHECK ("OFT_RESPUESTA" IS NOT NULL),
CONSTRAINT OFT_SISBEN_NIVEL_CHK CHECK (OFT_SISBEN_NIVEL in (1,2,3,4,5,6)),
CONSTRAINT OFT_SISBEN_TIPO_CHK CHECK (OFT_SISBEN_TIPO in (0,1)),
CONSTRAINT OFT_SUELDO_ACEPTARIA_NULL CHECK ("OFT_SUELDO_ACEPTARIA" IS NOT NULL),
CONSTRAINT OFT_TIEMPO_BUSQUEDA_NULL CHECK ("OFT_TIEMPO_BUSQUEDA" IS NOT NULL),
CONSTRAINT PAI_OFT_NULL CHECK ("PAI_ID" IS NOT NULL),
CONSTRAINT REG_OFT_NULL CHECK ("REG_ID" IS NOT NULL),
CONSTRAINT TDI_OFT_NULL CHECK ("TDI_ID" IS NOT NULL)
);



CREATE TABLE SPE.CENTRO_SPE (
CSPE_ID NUMBER(7,0),
CSPE_NOMBRE VARCHAR2(80),
CSPE_DIRECCION VARCHAR2(100),
CSPE_TEL VARCHAR2(30),
CSPE_TEL_ALT VARCHAR2(30),
CSPE_CORREO_E VARCHAR2(50),
CSPE_CORREO_E_ALT VARCHAR2(50),
CSPE_ESTADO NUMBER(1,0),
REG_ID NUMBER(2,0),
MPO_ID NUMBER(9,0),
TIPO_CSPE NUMBER(1,0) DEFAULT 0 ,
CSPE_ATENCION VARCHAR2(100),
CSPE_RESPONSABLE VARCHAR2(100),
CSPE_CODIGO_SOFIA NUMBER(5,0) DEFAULT 0,
CONSTRAINT CSPE_DIRECCION_NULL CHECK ("CSPE_DIRECCION" IS NOT NULL),
CONSTRAINT CSPE_ESTADO_CHK CHECK (CSPE_ESTADO in (0,1)),
CONSTRAINT CSPE_ESTADO_NULL CHECK ("CSPE_ESTADO" IS NOT NULL),
CONSTRAINT CSPE_ID_NULL CHECK ("CSPE_ID" IS NOT NULL),
CONSTRAINT CSPE_NOMBRE_NULL CHECK ("CSPE_NOMBRE" IS NOT NULL),
CONSTRAINT CSPE_PK PRIMARY KEY (CSPE_ID),
CONSTRAINT CSPE_TEL_NULL CHECK ("CSPE_TEL" IS NOT NULL),
CONSTRAINT CSPE_TIPO_NULL CHECK ("TIPO_CSPE" IS NOT NULL),
CONSTRAINT MPO_CSPE_NULL CHECK ("MPO_ID" IS NOT NULL),
CONSTRAINT REG_CSPE_NULL CHECK ("REG_ID" IS NOT NULL)
);

CREATE UNIQUE INDEX CSPE_PK ON SPE.CENTRO_SPE (CSPE_ID);


CREATE TABLE SPE.REGIONAL (
REG_ID NUMBER(2,0),
REG_NOMBRE VARCHAR2(50),
REG_DIRECCION VARCHAR2(100),
REG_TEL VARCHAR2(20),
REG_TEL_ALT VARCHAR2(20),
REG_FAX VARCHAR2(20),
REG_CORREO_E VARCHAR2(50),
REG_CORREO_E_ALT VARCHAR2(50),
MPO_ID NUMBER(9,0),
CONSTRAINT MPO_REG_NULL CHECK ("MPO_ID" IS NOT NULL),
CONSTRAINT REG_CORREO_E_NULL CHECK ("REG_CORREO_E" IS NOT NULL),
CONSTRAINT REG_DIRECCION_NULL CHECK ("REG_DIRECCION" IS NOT NULL),
CONSTRAINT REG_FAX_NULL CHECK ("REG_FAX" IS NOT NULL),
CONSTRAINT REG_ID_NULL CHECK ("REG_ID" IS NOT NULL),
CONSTRAINT REG_NOMBRE_NULL CHECK ("REG_NOMBRE" IS NOT NULL),
CONSTRAINT REG_PK PRIMARY KEY (REG_ID),
CONSTRAINT REG_TEL_NULL CHECK ("REG_TEL" IS NOT NULL)
);

CREATE UNIQUE INDEX REG_PK ON SPE.REGIONAL (REG_ID);




CREATE TABLE SPE.AC_COLOCACIONES (
OFT_ID NUMBER(10,0),
ENV_ID NUMBER(10,0),
TIPO_IDENTIFICACION VARCHAR2(4),
IDENTIFICACION NUMBER(20,0),
NOMBRES VARCHAR2(80),
PRIMER_APELLIDO VARCHAR2(80),
SEGUNDO_APELLIDO VARCHAR2(80),
GENERO VARCHAR2(20),
PAI_ID NUMBER(4,0),
DPT_ID NUMBER(8,0),
DEPARTAMENTO VARCHAR2(60),
MPO_ID NUMBER(15,0),
MUNICIPIO VARCHAR2(60),
SOLICITUD NUMBER(10,0),
OCU_ID NUMBER(8,0),
OCUPACION VARCHAR2(200),
DENOMINACION VARCHAR2(200),
EMP_ID NUMBER(8,0),
EMPRESA VARCHAR2(200),
FECHA_COLOCACION DATE,
ES_EGRESADO NUMBER(1,0),
FECHA_NACIMIENTO DATE,
MPO_ID_NACIMIENTO NUMBER(15,0)
);



CREATE TABLE SPE.AC_ORIENTADOS (
OFT_ID NUMBER(10,0),
HORIO_ID NUMBER(10,0),
TIPO_IDENTIFICACION VARCHAR2(4),
IDENTIFICACION NUMBER(20,0),
NOMBRES VARCHAR2(80),
PRIMER_APELLIDO VARCHAR2(80),
SEGUNDO_APELLIDO VARCHAR2(80),
GENERO VARCHAR2(20),
PAI_ID NUMBER(4,0),
DPT_ID NUMBER(8,0),
DEPARTAMENTO VARCHAR2(60),
MPO_ID NUMBER(15,0),
MUNICIPIO VARCHAR2(60),
FECHA_PRIMERA_ORIENTACION DATE,
FECHA_NACIMIENTO DATE,
MPO_ID_NACIMIENTO NUMBER(15,0)
);


CREATE TABLE SPE.AC_INSCRITOS (
OFT_ID NUMBER(10,0),
TIPO_IDENTIFICACION VARCHAR2(4),
IDENTIFICACION NUMBER(20,0),
NOMBRES VARCHAR2(80),
PRIMER_APELLIDO VARCHAR2(80),
SEGUNDO_APELLIDO VARCHAR2(80),
GENERO VARCHAR2(20),
PAI_ID NUMBER(4,0),
DPT_ID NUMBER(8,0),
DEPARTAMENTO VARCHAR2(60),
MPO_ID NUMBER(15,0),
MUNICIPIO VARCHAR2(60),
FECHA_INSCRIPCION DATE,
FECHA_NACIMIENTO DATE,
MPO_ID_NACIMIENTO NUMBER(15,0)
);


CREATE TABLE SPE.RUV (
TIPO_IDENTIFICACION VARCHAR2(4),
IDENTIFICACION NUMBER(20,0),
TPB_ID NUMBER(3,0),
ID_PERSONA NUMBER(20,0),
ESTADO NUMBER(1,0),
DESCRIPCION VARCHAR2(40)
);

CREATE INDEX IND_RUV ON SPE.RUV (TIPO_IDENTIFICACION,IDENTIFICACION);



CREATE TABLE SPE.TIPO_POBLACION_SOFIA_RUV (
TPB_ID VARCHAR2(3),
TIPO_POBLACION_SOFIA VARCHAR2(90)
);


CREATE TABLE SPE.MUNICIPIOS_CARACTERIZADOS (
MPO_ID NUMBER(9,0),
ES_PDET NUMBER(1,0),
ES_PNIS NUMBER(1,0),
RURALIDAD VARCHAR2(30)
);
